version: '3'
services:
    web:
        image: nginx:1.13.7
        volumes:
            - "/home/etc/ssl:/etc/ssl"
            - "/home/www:/var/www/html"
            - "/home/etc/nginx/vhost:/etc/nginx/conf.d"
            - "/home/etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
        ports:
            - "80:80"
            - "443:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/bash -c "nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - mysqldb
    php:
        image: hebidu/php-fpm:7.1
        restart: always
        volumes:
            - "/home/www/:/var/www/html"
            - "/home/etc/php:/usr/local/etc/php/conf.d"
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8077:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        restart: always
        depends_on:
            - mysqldb
    mysqldb:
        image: mysql:5.7
        container_name: ${MYSQL_HOST}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "8076:3306"
        volumes:
            - "/home/data/mysql:/var/lib/mysql"
            - "/home/etc/mysql:/etc/mysql/conf.d"